eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    com:
      netflix:
        discovery:
          shared:
            resolver:
              aws: WARN
    gateway:
      filters:
        JwtAuthFilter: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              routedefinition-locator: INFO
    reactor:
      netty: INFO
    root: INFO

server:
  port: 8080

spring:
  application:
    name: gateway


